Repository fun-eat/funeat-server, pull requests merged in 2024-01, with the labels that each got.

#2 feat: 깃허브액션을 이용한 CI/CD 구현
  .github/workflows/cicd-be.yml
  .github/workflows/test-fe.yml
  .github/workflows/test.yml
Labels: 🌎 Infra

#4 refactor: 상품 자동 완성 API 페이징 방식 변경
  src/main/java/com/funeat/product/application/ProductService.java
  src/main/java/com/funeat/product/dto/SearchProductsResponse.java
  src/main/java/com/funeat/product/persistence/ProductRepository.java
  src/main/java/com/funeat/product/presentation/ProductApiController.java
  src/main/java/com/funeat/product/presentation/ProductController.java
  src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
  src/test/java/com/funeat/acceptance/product/ProductSteps.java
  src/test/java/com/funeat/product/persistence/ProductRepositoryTest.java
Labels: 🔧 Refactor

#8 chore: 2.7.1 -> 3.2.1 springboot 마이그레이션
  .github/workflows/cicd-be.yml
  .github/workflows/test.yml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/com/funeat/admin/presentation/AdminLoginController.java
  src/main/java/com/funeat/admin/specification/AdminProductSpecification.java
  src/main/java/com/funeat/admin/specification/AdminReviewSpecification.java
  src/main/java/com/funeat/admin/util/AdminCheckInterceptor.java
  src/main/java/com/funeat/auth/application/AuthService.java
  src/main/java/com/funeat/auth/presentation/AuthApiController.java
  src/main/java/com/funeat/auth/presentation/AuthController.java
  src/main/java/com/funeat/auth/util/AuthArgumentResolver.java
  src/main/java/com/funeat/auth/util/AuthHandlerInterceptor.java
  src/main/java/com/funeat/banner/domain/Banner.java
  src/main/java/com/funeat/comment/domain/Comment.java
  src/main/java/com/funeat/comment/specification/CommentSpecification.java
  src/main/java/com/funeat/common/logging/LoggingAspect.java
  src/main/java/com/funeat/common/repository/BaseRepositoryImpl.java
  src/main/java/com/funeat/exception/presentation/GlobalControllerAdvice.java
  src/main/java/com/funeat/member/domain/Member.java
  src/main/java/com/funeat/member/domain/favorite/RecipeFavorite.java
  src/main/java/com/funeat/member/domain/favorite/ReviewFavorite.java
  src/main/java/com/funeat/member/dto/MemberRequest.java
  src/main/java/com/funeat/member/presentation/MemberApiController.java
  src/main/java/com/funeat/product/domain/Category.java
  src/main/java/com/funeat/product/domain/Product.java
  src/main/java/com/funeat/product/domain/ProductRecipe.java
  src/main/java/com/funeat/product/persistence/ProductSpecification.java
  src/main/java/com/funeat/recipe/domain/Recipe.java
  src/main/java/com/funeat/recipe/domain/RecipeImage.java
  src/main/java/com/funeat/recipe/dto/RecipeCommentCreateRequest.java
  src/main/java/com/funeat/recipe/dto/RecipeCreateRequest.java
  src/main/java/com/funeat/recipe/dto/RecipeFavoriteRequest.java
  src/main/java/com/funeat/recipe/persistence/RecipeRepository.java
  src/main/java/com/funeat/recipe/presentation/RecipeApiController.java
  src/main/java/com/funeat/recipe/util/RecipeDetailHandlerInterceptor.java
  src/main/java/com/funeat/recipe/util/RecipeHandlerInterceptor.java
  src/main/java/com/funeat/review/domain/Review.java
  src/main/java/com/funeat/review/domain/ReviewTag.java
  src/main/java/com/funeat/review/dto/ReviewCreateRequest.java
  src/main/java/com/funeat/review/dto/ReviewFavoriteRequest.java
  src/main/java/com/funeat/review/dto/SortingReviewRequest.java
  src/main/java/com/funeat/review/persistence/ReviewRepository.java
  src/main/java/com/funeat/review/persistence/ReviewRepositoryImpl.java
  src/main/java/com/funeat/review/presentation/ReviewApiController.java
  src/main/java/com/funeat/review/specification/SortingReviewSpecification.java
  src/main/java/com/funeat/tag/domain/Tag.java
  src/test/java/com/funeat/acceptance/auth/LoginSteps.java
  src/test/java/com/funeat/acceptance/review/ReviewSteps.java
  src/test/java/com/funeat/common/DataCleaner.java
  src/test/resources/application.yml
Labels: ✨ Feature

#10 chore: kotlin 설정 추가
  build.gradle
  build.gradle.kts
  settings.gradle
  settings.gradle.kts
Labels: ✨ Feature

#11 refactor: 상품 및 꿀조합 검색 결과 API 페이징 방식 변경
  src/main/java/com/funeat/product/application/ProductService.java
  src/main/java/com/funeat/product/dto/SearchProductResultsResponse.java
  src/main/java/com/funeat/product/persistence/ProductRepository.java
  src/main/java/com/funeat/product/presentation/ProductApiController.java
  src/main/java/com/funeat/product/presentation/ProductController.java
  src/main/java/com/funeat/recipe/application/RecipeService.java
  src/main/java/com/funeat/recipe/dto/SearchRecipeResultsResponse.java
  src/main/java/com/funeat/recipe/persistence/RecipeRepository.java
  src/main/java/com/funeat/recipe/presentation/RecipeApiController.java
  src/main/java/com/funeat/recipe/presentation/RecipeController.java
  src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
  src/test/java/com/funeat/acceptance/product/ProductSteps.java
  src/test/java/com/funeat/acceptance/recipe/RecipeAcceptanceTest.java
  src/test/java/com/funeat/acceptance/recipe/RecipeSteps.java
  src/test/java/com/funeat/fixture/RecipeFixture.java
  src/test/java/com/funeat/product/persistence/ProductRepositoryTest.java
  src/test/java/com/funeat/recipe/persistence/RecipeRepositoryTest.java
Labels: 🔧 Refactor

#14 fix: 검색 자동 완성 페이징 로직 수정
  src/main/java/com/funeat/product/application/ProductService.java
  src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
Labels: 🐛 Bug
