Repository fun-eat/funeat-server, pull requests merged in 2024-06, with the labels that each got.

#70 feat: 저장한 꿀조합 목록 조회 기능 추가
  src/main/java/com/funeat/member/dto/MemberBookmarkRecipeDto.java
  src/main/java/com/funeat/member/dto/MemberBookmarkRecipeProductDto.java
  src/main/java/com/funeat/member/dto/MemberBookmarkRecipeProductsDto.java
  src/main/java/com/funeat/member/dto/MemberBookmarkRecipesResponse.java
  src/main/java/com/funeat/member/dto/MemberRecipeProductDto.java
  src/main/java/com/funeat/member/presentation/MemberApiController.java
  src/main/java/com/funeat/member/presentation/MemberController.java
  src/main/java/com/funeat/recipe/application/RecipeService.java
  src/main/java/com/funeat/recipe/persistence/RecipeRepository.java
  src/test/java/com/funeat/acceptance/member/MemberAcceptanceTest.java
  src/test/java/com/funeat/acceptance/member/MemberSteps.java
  src/test/java/com/funeat/common/RepositoryTest.java
  src/test/java/com/funeat/fixture/RecipeFixture.java
  src/test/java/com/funeat/recipe/application/RecipeServiceTest.java
  src/test/java/com/funeat/recipe/persistence/RecipeRepositoryTest.java
Labels: ✨ Feature

#71 feat: 태그 검색 구현
  src/main/java/com/funeat/product/application/ProductService.java
  src/main/java/com/funeat/product/persistence/ProductRepository.java
  src/main/java/com/funeat/product/persistence/ProductRepositoryCustom.java
  src/main/java/com/funeat/product/persistence/ProductRepositoryImpl.java
  src/main/java/com/funeat/product/presentation/ProductApiController.java
  src/main/java/com/funeat/product/presentation/ProductController.java
  src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
  src/test/java/com/funeat/acceptance/product/ProductSteps.java
  src/test/java/com/funeat/fixture/ReviewFixture.java
  src/test/java/com/funeat/product/persistence/ProductRepositoryTest.java
Labels: ✨ Feature

#74 refactor: 상품 자동 완성 검색 API 수정
  src/main/java/com/funeat/product/dto/SearchProductDto.java
  src/main/java/com/funeat/product/dto/SearchProductsResponse.java
  src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
Labels: 🔧 Refactor

#75 refactor: 리뷰 랭킹 조회 API 수정
  src/main/java/com/funeat/member/persistence/ReviewFavoriteRepository.java
  src/main/java/com/funeat/review/application/ReviewService.java
  src/main/java/com/funeat/review/dto/RankingReviewDto.java
  src/main/java/com/funeat/review/dto/RankingReviewsResponse.java
  src/main/java/com/funeat/review/presentation/ReviewApiController.java
  src/main/java/com/funeat/review/presentation/ReviewController.java
  src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
  src/test/java/com/funeat/acceptance/review/ReviewSteps.java
  src/test/java/com/funeat/fixture/ReviewFixture.java
  src/test/java/com/funeat/review/application/ReviewServiceTest.java
Labels: 🔧 Refactor

#77 fix: 최신순 정렬을 사용하는 ServiceTest, RepositoryTest에 아이디 기준 내림차순 옵션 추가
  src/test/java/com/funeat/fixture/PageFixture.java
  src/test/java/com/funeat/recipe/application/RecipeServiceTest.java
  src/test/java/com/funeat/recipe/persistence/RecipeRepositoryTest.java
  src/test/java/com/funeat/review/application/ReviewServiceTest.java
Labels: 🐛 Bug
